db_driver=pdo_mysql
db_host=localhost
db_port=3306
db_name=__DB_NAME__
db_user=__DB_USER__
db_password=__DB_PWD__
db_table_prefix=bak_
db_backup_tables=true
db_backup_prefix=bak_
admin_firstname=ADMIN_FIRSTNAME        Admin first name.
admin_lastname=ADMIN_LASTNAME          Admin last name.
admin_username=__ADMIN__               Admin username.
admin_email=__EMAIL__                  Admin email.
admin_password=__PASSWORD__            Admin user.
mailer_from_name[=MAILER_FROM_NAME]    From name for email sent from Mautic.
mailer_from_email[=MAILER_FROM_EMAIL]  From email sent from Mautic.
mailer_transport[=MAILER_TRANSPORT]    Mail transport.
mailer_host=MAILER_HOST                SMTP host.
mailer_port=MAILER_PORT                SMTP port.
mailer_user=MAILER_USER                SMTP username.
mailer_password[=MAILER_PASSWORD]      SMTP password.
mailer_encryption[=MAILER_ENCRYPTION]  SMTP encryption (null|tls|ssl).
mailer_auth_mode[=MAILER_AUTH_MODE]    SMTP auth mode (null|plain|login|cram-md5).
mailer_spool_type=MAILER_SPOOL_TYPE    Spool mode (file|memory).
mailer_spool_path=MAILER_SPOOL_PATH    Spool path.