#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M

ynh_app_setting_set_default --key=php_memory_limit --value=512M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config/local.php media/files media/images translations"

chmod -R g+w "$install_dir/app/config/"
chmod -R g+w "$install_dir/media/files/"
chmod -R g+w "$install_dir/media/images/"
chmod -R g+w "$install_dir/translations/"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# FINISHING INSTALL
#=================================================
ynh_script_progression "Cleaning $app cach..."

pushd "$install_dir"
	ynh_exec_as_app php${php_version} bin/console cache:clear
	ynh_exec_as_app php${php_version} bin/console mautic:update:apply --finish
	ynh_exec_as_app php${php_version} bin/console doctrine:migration:migrate --no-interaction
	ynh_exec_as_app php${php_version} bin/console doctrine:schema:update --no-interaction --force
	ynh_exec_as_app php${php_version} in/console cache:clear
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
